### ISSUE TITLE
UI should show all system information fields (Machine details)

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical/maas-ui#1284]
https://bugs.launchpad.net/maas/+bug/1883337

The machine details page has a "System" card that shows the following metadata:

```
system_vendor
system_product
system_version
system_serial 
mainboard_vendor
mainboard_product
mainboard_firmware_version
mainboard_firmware_date
```

There's also `cpu_model` shown in the CPU card.

The list of possible metadata is:
```
system_vendor
system_product
system_family
system_version
system_sku
system_serial
cpu_model
mainboard_vendor
mainboard_product
mainboard_serial
mainboard_version
mainboard_firmware_vendor
mainboard_firmware_date
mainboard_firmware_version
chassis_vendor
chassis_type
chassis_serial
chassis_version
```

Not every machine will have every piece of metadata however. We should consider redesigning the system card to show only what's returned from the websocket in a dynamic way, e.g. we could:
- Split the card into three headers "System", "Mainboard" and "Chassis"
- Only show a header if it contains at least one piece of relevant metadata
- Only show the keys that are returned from the api instead of having an "Unknown" label if the key does not exist

**Comment by tmerten** [comment]
We are tracking this over here now: https://bugs.launchpad.net/maas/+bug/1883337
