### ISSUE TITLE
[Build] Add IP address to the networking card

### ISSUE THREAD

**Issue by amylily1011** [canonical/maas-ui#2851]
from #2601

**Comment by rayito** [comment]
[Zeplin link here](https://zpl.io/25zkeJJ)

**Comment by Caleb-Ellis** [comment]
Moving to icebox until we dedicate some time to build this. One thing to note that I don't think is outlined in the design - how should we handle IPv6 addresses which can be as long as 45 characters? e.g. `0123:4567:89ab:cdef:0123:4567:89ab:cdef`

**Comment by tmerten** [comment]
could check if there is enough space before asking UX again.
