### ISSUE TITLE
[UX/UI] There is no way to clear the event log for a Node

### ISSUE THREAD

**Issue by amylily1011** [canonical/maas-ui#2993]
## Summary
Based on https://bugs.launchpad.net/maas/+bug/1403080
It's possible for a Node to have tens of thousands of event log entries, but there's no way for a user to dispose of them should they no longer be needed.

For more info see this bug: https://bugs.launchpad.net/maas/+bug/1402237
(Node event log queries are slow (over 1 second) )

## Process
(Research for context and design an interaction for this feature)

## Current and expected result
- Users are able to clear the logs

**Comment by jurekh** [comment]
Unrelated to UI, improved log rotation/cleanup is on core feature backlog. The issue can be closed.
