### ISSUE TITLE
Looking for Help- MAAS UI Machines, discoveries etc Data

### ISSUE THREAD

**Issue by ipchaube** [canonical/maas-ui#3176]
Hi Their,
I am looking for help to understand how we are reading data for Machines, discoveries, etc on UI. Please see if you can describe a bit ui data flow. I have a new API that has to go for UI and data needs to be displayed on UI.

Thanks,
Indu

**Comment by Caleb-Ellis** [comment]
We should update our HACKING.md with a lot of the stuff we have in our onboarding doc in order to answer questions like these.

**Comment by anthonydillon** [comment]
@huwshimi @petermakowski would you mind taking a look at this issue and adding an estimation please?

**Comment by huwshimi** [comment]
Hi @ipchaube are you still in need of this information? Is there something specific you're stuck with or just after some general info on data flow?

**Comment by ipchaube** [comment]
Thanks for reply, I had figured this out.

**Comment by huwshimi** [comment]
> Thanks for reply, I had figured this out.

Great, apologies that we didn't get back to you sooner!
