### ISSUE TITLE
Form buttons get squashed on smaller screen sizes

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical/maas-ui#3334]
This is only an issue with the forms that include a "Save and add another" button

<img width="435" alt="Screen Shot 2021-11-25 at 1 54 05 pm" src="https://user-images.githubusercontent.com/361637/143372239-9abf403e-74d7-4d20-9016-b14c0ec45bb1.png">
<img width="371" alt="Screen Shot 2021-11-25 at 1 54 12 pm" src="https://user-images.githubusercontent.com/361637/143372244-3b870cf7-0adf-422f-96b6-1073c754b9b7.png">

_Originally posted by @huwshimi in https://github.com/canonical-web-and-design/maas-ui/pull/3331#pullrequestreview-815517294_

**Comment by petermakowski** [comment]
@Jay-Topher steps to reproduce:
1. go to devices page
2. 2. click Add device
3. Change viewport size to a width of 400px

<img width="399" alt="image" src="https://user-images.githubusercontent.com/7452681/217757288-8f6d9707-12e4-4057-9a23-f3bd878c6d17.png">
