### ISSUE TITLE
New logo mark larger than it should be

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/maas-ui#3933]
Brand have flaged that the logo mark s taller than the accompanying word mark:
<img width="236" alt="image" src="https://user-images.githubusercontent.com/2741678/168072877-f313109b-b538-463a-a915-37a8a13e69db.png">

For reference, @waynecrosby has provided the original logo:
<img width="1044" alt="image" src="https://user-images.githubusercontent.com/2741678/168073076-2cf30d7b-9547-4523-93de-5ab6b2458158.png">

**Comment by petermakowski** [comment]
I think this affects all instances where we use the new Navigation component is used.

The Canonical text is also not aligned with the logo mark in the example on vanilla (unless the alignment is meant to vary for each instance?)
https://vanillaframework.io/docs/patterns/navigation
<img width="430" alt="image" src="https://user-images.githubusercontent.com/7452681/168075814-f3e05fec-5123-4ede-a581-221a420fa758.png">

@lyubomir-popov Could you confirm that the above is incorrect, in which case an issue should be probably filed on https://github.com/canonical-web-and-design/vanilla-framework

**Comment by anthonydillon** [comment]
Should this be the stacked logo with Canonical on top of MAAS?

**Comment by huwshimi** [comment]
> Should this be the stacked logo with Canonical on top of MAAS?

I checked with design about this and they confirmed that it should be side-by-side instead of stacked: https://www.figma.com/file/BSP7FqnRMcMvO7kCozJKUa/Ubuntu.com-navigation-update-Iteration-9?node-id=1431%3A3827

**Comment by petermakowski** [comment]
Fixed.
