### ISSUE TITLE
Add discovery from Dashboard stuck on spinner

### ISSUE THREAD

**Issue by sparkiegeek** [canonical/maas-ui#4387]
**Describe the bug**
When attempting to Add Discovery from the Dashboard, in latest main, all you get is a spinner and no actual form pop-op.

**maas-ui version**
Seems much harder to find this out now - what's the way of finding out from a browser connected to the UI?

**MAAS version**
3.3.0~alpha1-12573-g.0b0882053

**LP issue**

**To Reproduce**
1. Go to 'http://bolla.internal:5240/MAAS/r/dashboard'
2. Click on a row's Action :arrow_down_small: then `Add discovery...`
4. See spinner and no actual form

**Expected behavior**
Form appears to fill in the details of the device

**Screenshots**
![image](https://user-images.githubusercontent.com/246192/188588640-47a4ba35-650a-4f4e-91b3-694747ae8e80.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 LTS
 - Browser: Firefox
 - Version: 104.0.1

**Additional context**

**Comment by petermakowski** [comment]
> **maas-ui version** Seems much harder to find this out now - what's the way of finding out from a browser connected to the UI?

@sparkiegeek  It's displayed in the controller page `MAAS/r/controllers` in the VERSION/CHANNEL column.

**Comment by petermakowski** [comment]
This is now resolved by https://github.com/canonical/maas-ui/pull/4402

**Comment by sparkiegeek** [comment]
> > **maas-ui version** Seems much harder to find this out now - what's the way of finding out from a browser connected to the UI?
> 
> @sparkiegeek It's displayed in the controller page `MAAS/r/controllers` in the VERSION/CHANNEL column.

that's not the **maas-ui version**, that's the **MAAS version** (i.e. it doesn't reference a commit here)

**Comment by petermakowski** [comment]
> > > **maas-ui version** Seems much harder to find this out now - what's the way of finding out from a browser connected to the UI?
> > 
> > 
> > @sparkiegeek It's displayed in the controller page `MAAS/r/controllers` in the VERSION/CHANNEL column.
> 
> that's not the **maas-ui version**, that's the **MAAS version** (i.e. it doesn't reference a commit here)

Oh right, in that case it might be best to add the commit hash during the front-end build and expose it somewhere in the UI, or just the browser console. Will follow up in: https://github.com/canonical/maas-ui/issues/4404
