### ISSUE TITLE
Expose maas-ui version info

### ISSUE THREAD

**Issue by petermakowski** [canonical/maas-ui#4404]
We need to add the information about the the maas-ui version (if not already included) and expose it either somewhere in the UI or just the browser console initially.

> > **maas-ui version** Seems much harder to find this out now - what's the way of finding out from a browser connected to the UI?
> 
> @sparkiegeek It's displayed in the controller page `MAAS/r/controllers` in the VERSION/CHANNEL column.

that's not the **maas-ui version**, that's the **MAAS version** (i.e. it doesn't reference a commit here)

_Originally posted by @sparkiegeek in https://github.com/canonical/maas-ui/issues/4387#issuecomment-1241936509_

**Comment by sparkiegeek** [comment]
in ye-olde Angular.JS days, it used to be written to console somewhere near the start of the app

**Comment by sparkiegeek** [comment]
See https://github.com/canonical/maas-ui/pull/930
