### ISSUE TITLE
KVM Page Fails to load for nonadmin user with error “An unexpected error has occurred, please try refreshing your browser window.”

### ISSUE THREAD

**Issue by matjazp** [canonical/maas-ui#4441]
**Describe the bug**
KVM Page Fails to load for nonadmin user with error “An unexpected error has occurred, please try refreshing your browser window.”

**maas-ui version**
3.2.6?

**MAAS version**
3.2.6

**LP issue**
https://bugs.launchpad.net/maas/+bug/1991784

**To Reproduce**
non admin user gets this error when clicking on KVM tab. Admin user loads page normally.

[Error] TypeError: undefined is not an object (evaluating 'e.power_parameters.project')
(anonymous function) — ui.js:112:673792
map
JP — ui.js:112:673521
es — ui.js:51:58878
Bo — ui.js:51:111315
jc — ui.js:51:98327
vc — ui.js:51:98255
gc — ui.js:51:98115
lc — ui.js:51:95105
lc
(anonymous function) — ui.js:51:44771
(anonymous function) — ui.js:59:3768
Va — ui.js:51:44719
qa — ui.js:51:44651
uc — ui.js:51:95423
notify — ui.js:112:36799
notifyNestedSubs — ui.js:112:37400
a — ui.js:112:37233
f — ui.js:112:20252
(anonymous function) — ui.js:112:65168
(anonymous function) — ui.js:112:58311
Fr — ui.js:112:56260
Hr — ui.js:112:56469
Ur — ui.js:112:56314
(anonymous function) — ui.js:112:58263
(anonymous function) — ui.js:112:62832
f — ui.js:112:63751
d — ui.js:112:63263
c — ui.js:112:63536
m — ui.js:112:62120
(anonymous function) — ui.js:112:61655
d — ui.js:112:63251
c — ui.js:112:63536
(anonymous function) — ui.js:112:59064
(anonymous function) — ui.js:112:62832
f — ui.js:112:63751
d — ui.js:112:63263
ha — ui.js:112:63026
(anonymous function) — ui.js:112:59033
(anonymous function) — ui.js:112:62832
f — ui.js:112:63751
d — ui.js:112:63263
c — ui.js:112:63536
(anonymous function) — ui.js:112:59064
(anonymous function) — ui.js:112:62832
f — ui.js:112:63751
d — ui.js:112:63263
c — ui.js:112:63536
o — ui.js:112:58112
put — ui.js:112:57173
(anonymous function) — ui.js:126:10798
(anonymous function) — ui.js:126:10889
(anonymous function) — ui.js:126:2020

	to (475.1f0384a47ef41eb51eb8.js:2:464289)
	(anonymous function) (475.1f0384a47ef41eb51eb8.js:2:466542)
	oi (475.1f0384a47ef41eb51eb8.js:2:429768)
	Bs (475.1f0384a47ef41eb51eb8.js:2:452395)
	jc (475.1f0384a47ef41eb51eb8.js:2:480462)
	vc (475.1f0384a47ef41eb51eb8.js:2:480390)
	gc (475.1f0384a47ef41eb51eb8.js:2:480253)
	lc (475.1f0384a47ef41eb51eb8.js:2:477240)
	lc
	(anonymous function) (475.1f0384a47ef41eb51eb8.js:2:426946)
	(anonymous function) (475.1f0384a47ef41eb51eb8.js:2:504139)
	Va (475.1f0384a47ef41eb51eb8.js:2:426892)
	qa (475.1f0384a47ef41eb51eb8.js:2:426827)
	uc (475.1f0384a47ef41eb51eb8.js:2:477561)
	notify (475.1f0384a47ef41eb51eb8.js:2:1019590)
	notifyNestedSubs (475.1f0384a47ef41eb51eb8.js:2:1020008)
	a (475.1f0384a47ef41eb51eb8.js:2:1019439)
	f (475.1f0384a47ef41eb51eb8.js:2:1009129)
	(anonymous function) (475.1f0384a47ef41eb51eb8.js:2:2107171)
	(anonymous function) (475.1f0384a47ef41eb51eb8.js:2:1040383)
	Fr (475.1f0384a47ef41eb51eb8.js:2:1038336)
	Hr (475.1f0384a47ef41eb51eb8.js:2:1038543)
	Ur (475.1f0384a47ef41eb51eb8.js:2:1038391)
	(anonymous function) (475.1f0384a47ef41eb51eb8.js:2:1040338)
	(anonymous function) (475.1f0384a47ef41eb51eb8.js:2:1044854)
	f (475.1f0384a47ef41eb51eb8.js:2:1045768)
	d (475.1f0384a47ef41eb51eb8.js:2:1045280)
	c (475.1f0384a47ef41eb51eb8.js:2:1045553)
	m (475.1f0384a47ef41eb51eb8.js:2:1044162)
	(anonymous function) (475.1f0384a47ef41eb51eb8.js:2:1043318)
	d (475.1f0384a47ef41eb51eb8.js:2:1045268)
	c (475.1f0384a47ef41eb51eb8.js:2:1045553)
	(anonymous function) (475.1f0384a47ef41eb51eb8.js:2:1041136)
	(anonymous function) (475.1f0384a47ef41eb51eb8.js:2:1044854)
	f (475.1f0384a47ef41eb51eb8.js:2:1045768)
	d (475.1f0384a47ef41eb51eb8.js:2:1045280)
	ha (475.1f0384a47ef41eb51eb8.js:2:1045045)
	(anonymous function) (475.1f0384a47ef41eb51eb8.js:2:1041105)
	(anonymous function) (475.1f0384a47ef41eb51eb8.js:2:1044854)
	f (475.1f0384a47ef41eb51eb8.js:2:1045768)
	d (475.1f0384a47ef41eb51eb8.js:2:1045280)
	c (475.1f0384a47ef41eb51eb8.js:2:1045553)
	(anonymous function) (475.1f0384a47ef41eb51eb8.js:2:1041136)
	(anonymous function) (475.1f0384a47ef41eb51eb8.js:2:1044854)
	f (475.1f0384a47ef41eb51eb8.js:2:1045768)
	d (475.1f0384a47ef41eb51eb8.js:2:1045280)
	c (475.1f0384a47ef41eb51eb8.js:2:1045553)
	o (475.1f0384a47ef41eb51eb8.js:2:1040184)
	put (475.1f0384a47ef41eb51eb8.js:2:1039247)
	(anonymous function) (475.1f0384a47ef41eb51eb8.js:2:2094399)
	(anonymous function) (475.1f0384a47ef41eb51eb8.js:2:2094491)
	(anonymous function) (475.1f0384a47ef41eb51eb8.js:2:2086326)

**Comment by petermakowski** [comment]
Thanks for reporting this @matjazp
Launchpad is usually the place to report these.
Closing in favour of https://github.com/canonical/maas-ui/issues/4442 which is linked to LP issue.
