### ISSUE TITLE
Unnecessary repeated machine.count calls

### ISSUE THREAD

**Issue by sparkiegeek** [canonical/maas-ui#4488]
**Describe the bug**
When loading the machine listing page, 6 calls are made to `machine.count`, four are without parameters, two are with `{"filter": {}}`

All 6 get the same response with `{"count": 15}' or however many machines are available

**maas-ui version**
 3.3.0~beta1

**MAAS version**
 3.3.0~beta1

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'http://bolla.internal:5240/MAAS/r/machines'
2. Open DevTools, Network and find the websocket
3. Look at the Response tab
4. Filter for machine.count
5. See 6 `machine.count`
6. 
**Expected behaviour**
See one `machine.count` call

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 LTS
 - Browser: Firefox
 - Version: 105.0.2

**Additional context**

**Comment by petermakowski** [comment]
Related: https://github.com/canonical/maas-ui/issues/4274
