### ISSUE TITLE
Missing space in domain subheading

### ISSUE THREAD

**Issue by petermakowski** [canonical/maas-ui#4567]
There's no space between the number of hosts and resource records in Domain subheading

<img width="257" alt="image" src="https://user-images.githubusercontent.com/7452681/203000404-6178b886-b61e-4aa9-b130-44876c6f7f28.png">

example URL (bolla)
`/MAAS/r/domain/5`

**Comment by suryakanthrai** [comment]
Hi 

Can i get help in setting the environment in my local environment. I am attaching the screenshot of it. Can we use NPM instead of Yarn?
![image](https://user-images.githubusercontent.com/46310284/203737901-899664f3-6966-4a47-b908-deb095bbfb48.png)

**Comment by petermakowski** [comment]
> Hi
> 
> Can i get help in setting the environment in my local environment. I am attaching the screenshot of it. Can we use NPM instead of Yarn?

Sure! Actually it's best to use `dotrun`, but it only runs on Linux/macOS. Once you install it you can simply run `dotrun` command in maas-ui directory to get started.

On Windows you'll need to use `yarn`.

**Comment by suryakanthrai** [comment]
Hi 
I have tried to do it ubuntu machine when i give dotrun command  in the terminal. it throwing the below error. where to give the port number? I have installed docker and I am able to launch it 
![Screenshot from 2022-11-26 09-06-17](https://user-images.githubusercontent.com/46310284/204071032-a62b7964-f774-424f-a8b7-ed67fdba12d3.png)

**Comment by petermakowski** [comment]
> Hi I have tried to do it ubuntu machine when i give dotrun command in the terminal. it throwing the below error. where to give the port number? I have installed docker and I am able to launch it 

Try to stop the given container in docker (or simply all containers) and try again?

This is a known issue with dotrun: https://github.com/canonical/dotrun/issues/107

**Comment by petermakowski** [comment]
This is now fixed.

**Comment by suryakanthrai** [comment]
This is awesome let me give it a try. Looking forward to connect with you peter can i have you mail or social handle
