### ISSUE TITLE
Outdated list of tags on machine selection update

### ISSUE THREAD

**Issue by petermakowski** [canonical/maas-ui#4600]
**Describe the bug**
Sometimes the list of tags in the tags form on the machine list page is incorrect after you update your selection after the form is opened

**maas-ui version**
maas-ui 3.3.0 cd8267662044c6308042f0e721723b94682da291

**To Reproduce**
1. Go to machine listing page
2. Set Grouping in a way that shows you multiple groups of machines on a page
4. Select a group of machines (ensure there are existing tags assigned to machines in that group)
5. Click on Take action > Tag...
6. In addition, select a single machine outside of the group that you just selected (ensure there are existing tags assigned to that machine)
7. Deselect the machine you just selected
8. "No tags are currently assigned to the selected machines." message is displayed

**Expected behavior**
No "No tags are currently assigned to the selected machines." message is displayed. List of tags assigned to selected machines is displayed instead.

**Comment by amylily1011** [comment]
Great discovery @petermakowski. Should I attach this to a jira ticket? And we can work on this on the next pulse?

**Comment by petermakowski** [comment]
> Great discovery @petermakowski. Should I attach this to a jira ticket? And we can work on this on the next pulse?

This is already fixed 🙈 
I'm fine with creating a JIRA ticket, but I thought that we decided to keep bugs on GitHub (at least that's what Ant suggested)?
