### ISSUE TITLE
Updating kernel parameters has buggy UI

### ISSUE THREAD

**Issue by axinojolais** [canonical/maas-ui#4690]
**Describe the bug**
When I update the kernel parameters in `/MAAS/r/settings/configuration/kernel-parameters`, any change I make gets removed from the input line when I press Save (even though the changes are actually saved in MAAS), and I have to reload the page to see the changes.

**maas-ui version**
3.2.6-12016-g.19812b4da

**MAAS version**
3.2.6-12016-g.19812b4da

**Comment by petermakowski** [comment]
Thanks for reporting! This has been fixed in MAAS 3.3
https://github.com/canonical/maas-ui/issues/4417
https://bugs.launchpad.net/maas/+bug/1990649
