### ISSUE TITLE
"Examples: :no_entry: maas-prod" is misleading

### ISSUE THREAD

**Issue by nobuto-m** [canonical/maas-ui#4785]
**Describe the bug**

In the MAAS config, there is a section about examples you can use as "MAAS name".

> Examples:
> ⛔ maas-prod
> my-maas ⚠️ no-deploys

I initially thought that I cannot use `maas-prod` as my MAAS name since it was prefixed with the `⛔` sign and wondered why I cannot use `maas-prod` which totally looks valid.

I know what those examples mean by now, but in any case, `⛔` and `⚠️` are usually the last symbols we want to see in a software UI in general because it suggests a system error or a warning we need to handle whenever we see it.

Again, I know what the examples mean but there may be better examples than those.

https://github.com/canonical/maas-ui/blob/8f974413d0a8dc2a13654042bad614fc620cdeb7/src/app/settings/views/Configuration/GeneralForm/GeneralForm.tsx#L123-L124

**maas-ui version**
maas-ui 3.3.0 acde9f13b45dd515b3d9638545bf82d282d7d5a2

^^^ on a side note, this version was hard to find since there is no instruction in the bug report template.

**MAAS version**
3.3.0-13159-g.1c22f7beb-0ubuntu1~22.04.1

**LP issue**
N/A

**To Reproduce**

**Expected behavior**

**Screenshots**

![Screenshot from 2023-02-24 15-53-54](https://user-images.githubusercontent.com/4356209/221180502-0adfbaef-cac8-4248-b0fb-a3d24ce29e93.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by petermakowski** [comment]
@amylily1011 shall we remove the first example with the ⛔ emoji since it seems to be confusing users?

**Comment by ndv99** [comment]
Either that or just change it to a different emote, maybe 🌐 ?

**Comment by amylily1011** [comment]
Yeah, maybe the first example could be `US-west-2 🇺🇸 MAAS-prod` and the second one can be `my-maas ❗ no-deploys` as Nick mentioned.
