### ISSUE TITLE
Unusual spacing in parsing of multiple distributions or components when adding a package repository

### ISSUE THREAD

**Issue by wyattrees** [canonical/maas-ui#5464]
**Describe the bug**
When adding a new package repository with multiple distributions or components via the MAAS UI, you need to enter them comma-separated, but with the spaces before the commas, like so: `focal ,jammy ,noble`

**maas-ui version**
3.6.0

**MAAS version**
3.4

**LP issue**
N/A

**To Reproduce**

1. Go to Settings->Package Repos->Add Repository
2. For both the Distributions and Components sections, enter any values separated with commas, but without the space before the comma (e.g. `focal, jammy, noble` or `focal,jammy,noble`)
3. Click Save Repository
4. Inspecting the WS request sent to MAAS will show a singleton list, `["focal, jammy, noble"]`. If you use spaces before the commas in step 2, the list is `["focal", "jammy", "noble"]`

**Expected behavior**
The list sent to MAAS is `["focal", "jammy", "noble"]` when spaces are either omitted or placed after commas.

**Screenshots**
![ui-parsing](https://github.com/canonical/maas-ui/assets/25443786/e8a526ff-5dcd-4a0d-8b94-326dfd5ad2c3)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser Chrome
 - Version 126.0.6478.55-1

**Comment by petermakowski** [comment]
Thanks for reporting this! FYI we now use launchpad for bug tracking in maas-ui. https://bugs.launchpad.net/maas-ui
