### ISSUE TITLE
Machine's last commission time shown as time since first commission

### ISSUE THREAD

**Issue by wyattrees** [canonical/maas-ui#5465]
**Describe the bug**
If a machine has had multiple commissioning events on different dates, the UI will display "Last commissioned: {time since _first_ commission event}"

**maas-ui version**
3.6.0

**MAAS version**
3.4

**LP issue**
LP#2069226

**To Reproduce**
1. Find a machine with commissioning events on different days (in labmaas, `chladni` is an example)
2. Click on the machine name, then the "Commissioning" tab
3. Note the "Last commissioned" time in the bottom right corner corresponds to the time since the earliest event in the table

**Expected behavior**
The "Last commissioned" time corresponds to the time since the _latest_ commissioning event

**Screenshots**
From the LP bug: 
<img width="1569" alt="last-commissioned-bug" src="https://github.com/canonical/maas-ui/assets/25443786/55df806f-62e0-499e-b2ac-2de03a57c695">

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser chrome
 - Version 126.0.6478.55-1

**Comment by petermakowski** [comment]
Thanks for reporting this! FYI we now use launchpad for bug tracking in maas-ui. https://bugs.launchpad.net/maas-ui
