### ISSUE TITLE
Investigate why session never expires, i.e. users never need to log back in

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical/maas-ui#864]
Could be something to do with the websocket connection, so the session never becomes inactive.

**Comment by petermakowski** [comment]
I looked into how we handle the WebSocket connection and found an issue that may be related: https://github.com/canonical-web-and-design/maas-ui/issues/3930

**Comment by tmerten** [comment]
This should be a byproduct of implementing [configurable session timeouts](https://warthogs.atlassian.net/jira/software/c/projects/MAASENG/boards/302?modal=detail&selectedIssue=MAASENG-1121&search=timeout)

**Comment by petermakowski** [comment]
Just had a quick catchup with @ndv99 on the current behaviour in the app and how we want to solve this.

## MAAS UI app behaviour once the session times out
### Current
A user can keep interacting with the app after the session has timed out including navigating to different pages and making requests via websocket for which all data is still being returned as normal.
A user is redirected to a login page only once they refresh the page. 

### Expected
What should happen once the session times out is either:
- the websocket connection is immediately closed from the back-end
- any further websocket requests result in an error message being returned

As soon as either of the above happen the app should either redirect a user to the login screen or display an error message notification that the session has timed out. 

TODO:
- [ ] to find out a way of setting the session timeout to a value smaller than 1 hour to allow for easier testing
- [ ] @ndv99 to confirm the current behaviour of the app from the moment a user logs in up until the session expires and they attempt to make further interactions on the page. This should include recording network activity for websockets/REST API using Wireshark
