### ISSUE TITLE
Build close link at bottom of script src code blocks

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical/maas-ui#878]
See #189 for design

**Comment by petermakowski** [comment]
@Jay-Topher Go to `/MAAS/r/settings/scripts/commissioning` to see list of scripts this is regarding. 
We need to add a "Close snippet" button at the end of the expanded script to make collapsing scripts easier, see design below:
https://github.com/canonical/maas-ui/issues/189#issuecomment-591457784
