### ISSUE TITLE
[UX] MAAS could more cleanly handle releasing a KVM Host

### ISSUE THREAD

**Issue by lilyvidenova** [canonical/maas-ui#904]
[LP bug 1865072](https://bugs.launchpad.net/maas/+bug/1865072)

I deployed a host and selected the "Register as KVM Host" option which deployed the node and created a pod.

Now when I try to release the host, I get an error that tells me I have to delete the pod first.

That's fine, but it would be a bit cleaner, IMO, if instead (or optionally) I could do this:

Select node
Issue Release
Get warning "You are attempting to release a KVM Host attached to $POD_NAME. Releasing this host will delete all VMs and remove this host from the Pod Pool, do you wish to continue?"
Select Yes
MAAS does the right thing and removes the pod, and releases the node.

That would give me the option to easily remove a KVM host, OR change my mind and not remove the host, without forcing me to jump through extra hoops unnecessarily.

**Comment by Caleb-Ellis** [comment]
Still valid

**Comment by tmerten** [comment]
This is now tracked here: https://bugs.launchpad.net/maas-ui/+bug/1865072
